### ISSUE TITLE
Use in Authoring Tool?

### ISSUE THREAD

**Issue by hmaffin** [cgkineo/adapt-questionStrip#1]
Hi guys,

I tried this out on AT 0.1.4 and it goes great but when I preview I get the spinning loading wheel of death on the page it's on. Is it just not suited to the AT or is there something that can be tweaked to make it work? Nothing reported in the Command Prompt.

Cheers :)

**Comment by hmaffin** [comment]
Just tried this again - firstly upload failed it said plugin already exists, when it should just be upgrading the version - plus now and all I get is a blank page for the component properties.

**Comment by moloko** [comment]
There's not really been any updates since you last tried it I'm afraid... just a couple of things to do with registering it with the plugin repository. Maybe the AT has got confused because it hasn't changed??

**Comment by hmaffin** [comment]
Cheers Matt!

**Comment by moloko** [comment]
closing as issue is so old it's unlikely to still be relevant
