### ISSUE TITLE
Authoring tool 0.5.0

### ISSUE THREAD

**Issue by SteveX** [cgkineo/adapt-questionStrip#2]
After installing and adding the component to a page the authoring tool shows a modal message 
`undefined is not a constructor (evaluating 'new(0,this.schema.type)(e)')`

**Comment by moloko** [comment]
not a very helpful error, unfortunately. I can see a couple of obvious mistakes though - hopefully fixing those should solve it.

**Comment by moloko** [comment]
@SteveX  please try the new release and let us know if that's any better

**Comment by SteveX** [comment]
Thanks Matt, that seems to be working now, much appreciated.

To install successfully in the authoring tool I need to change bower.json to read "framework": ">=2.0.0"

**Comment by moloko** [comment]
Excellent news, thanks for confirming
> To install successfully in the authoring tool I need to change bower.json to read "framework": ">=2.0.0"

Whoops missed that - good catch. Now fixed.
